---

#knobs:
    # log_level_debug: true
    # log_to_console: false
mqtt:
    host: 192.168.0.143
    client_id: kasa_mqtt
    #username:
    #password:
    #reconnect_interval:

globals:
    topic_format: /{}/switch

devices:
    shed_plug:
      host: 192.168.0.190
      #topic:

    cabinets_left:
      host: 192.168.0.160

    cabinets_right:
      host: 192.168.0.192

    porch_light:
      host: 192.168.0.137
...
